import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { useToast } from "@/hooks/use-toast";

// Simple tax report detection
export const isTaxReport = (content: string): boolean => {
  return content.includes('✅ **Scenario Title:**') || 
         content.includes('✅ Scenario Title:') ||
         content.includes('📌 **Key Strategies:**') ||
         content.includes('🛠 **Actionable Next Steps:**') ||
         content.includes('💰 **Estimated Potential Tax Savings:**');
};

// Client-side PDF export using browser's print functionality
const exportToPrint = (content: string) => {
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    throw new Error('Popup blocked - please allow popups for PDF export');
  }

  // Convert markdown-style content to basic HTML
  const htmlContent = content
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.*?)\*/g, '<em>$1</em>')
    .replace(/^- (.*)/gm, '• $1')
    .replace(/^\d+\. (.*)/gm, '<div style="margin-left: 20px;">$1</div>')
    .replace(/\n/g, '<br>');

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Tax Planning Report</title>
      <style>
        @media print {
          body { margin: 0; padding: 20px; }
          .no-print { display: none; }
        }
        body {
          font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
          line-height: 1.6;
          color: #333;
          max-width: 800px;
          margin: 0 auto;
          padding: 20px;
        }
        h1, h2, h3 { color: #2563eb; }
        strong { color: #1f2937; }
        .header {
          text-align: center;
          border-bottom: 2px solid #e5e7eb;
          padding-bottom: 20px;
          margin-bottom: 30px;
        }
        .content {
          white-space: pre-line;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>Tax Planning Report</h1>
        <p>Generated by AITaxMD • ${new Date().toLocaleDateString()}</p>
      </div>
      <div class="content">${htmlContent}</div>
      <div class="no-print" style="margin-top: 30px; text-align: center;">
        <p><small>Use Ctrl+P or Cmd+P to print, or use your browser's File → Print menu</small></p>
      </div>
    </body>
    </html>
  `;

  printWindow.document.write(html);
  printWindow.document.close();
  printWindow.focus();
  
  // Auto-trigger print dialog after a short delay
  setTimeout(() => {
    printWindow.print();
  }, 500);
};

interface UsePdfExportOptions {
  messageId?: number;
  content: string;
  showToast?: boolean;
}

export const usePdfExport = ({ messageId, content, showToast = true }: UsePdfExportOptions) => {
  const { toast } = useToast();

  const mutation = useMutation({
    mutationFn: async () => {
      // If no messageId, use simple client-side export
      if (!messageId) {
        exportToPrint(content);
        return { success: true, type: 'client' };
      }
      
      // Try server-based export first
      try {
        const response = await fetch(`/api/export/pdf/message/${messageId}`, {
          method: "POST",
          credentials: "include",
        });
        
        if (!response.ok) {
          // If server fails, fallback to client-side export
          console.warn('Server PDF export failed, falling back to client-side export');
          exportToPrint(content);
          return { success: true, type: 'client' };
        }
        
        const blob = await response.blob();
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `tax-plan-${messageId}.pdf`;
        document.body.appendChild(a);
        a.click();
        window.URL.revokeObjectURL(url);
        document.body.removeChild(a);
        
        return { success: true, type: 'server', blob };
      } catch (error) {
        // Fallback to client-side export on any error
        console.warn('Server PDF export error, falling back to client-side export:', error);
        exportToPrint(content);
        return { success: true, type: 'client' };
      }
    },
    onSuccess: (result) => {
      if (!showToast) return;
      
      toast({
        title: result?.type === 'server' ? "PDF Downloaded" : "Print Dialog Opened",
        description: result?.type === 'server' ? 
          "Your tax plan has been exported as PDF." : 
          "Use your browser's print dialog to save as PDF.",
      });
    },
    onError: (error) => {
      if (!showToast) return;
      
      toast({
        title: "Export Failed",
        description: error instanceof Error ? error.message : "Could not export PDF. Please try again.",
        variant: "destructive",
      });
    },
  });

  return {
    exportPdf: mutation.mutate,
    isExporting: mutation.isPending,
    error: mutation.error,
    isSuccess: mutation.isSuccess,
  };
};