import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { apiRequest } from "@/lib/queryClient";
import { Button } from "@/components/ui/button";
import { 
  Download, 
  Mail, 
  Copy, 
  FileText,
  Share2,
  Check,
  Loader2
} from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";

interface ExportButtonsProps {
  messageId?: number;
  content: string;
  className?: string;
}

// Simple tax report detection
const isTaxReport = (content: string): boolean => {
  return content.includes('✅ **Scenario Title:**') || 
         content.includes('✅ Scenario Title:') ||
         content.includes('📌 **Key Strategies:**') ||
         content.includes('🛠 **Actionable Next Steps:**') ||
         content.includes('💰 **Estimated Potential Tax Savings:**');
};

// Client-side PDF export using browser's print functionality
const exportToPrint = (content: string) => {
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    throw new Error('Popup blocked - please allow popups for PDF export');
  }

  // Convert markdown-style content to basic HTML
  const htmlContent = content
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.*?)\*/g, '<em>$1</em>')
    .replace(/^- (.*)/gm, '• $1')
    .replace(/^\d+\. (.*)/gm, '<div style="margin-left: 20px;">$1</div>')
    .replace(/\n/g, '<br>');

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Tax Planning Report</title>
      <style>
        @media print {
          body { margin: 0; padding: 20px; }
          .no-print { display: none; }
        }
        body {
          font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
          line-height: 1.6;
          color: #333;
          max-width: 800px;
          margin: 0 auto;
          padding: 20px;
        }
        h1, h2, h3 { color: #2563eb; }
        strong { color: #1f2937; }
        .header {
          text-align: center;
          border-bottom: 2px solid #e5e7eb;
          padding-bottom: 20px;
          margin-bottom: 30px;
        }
        .content {
          white-space: pre-line;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>Tax Planning Report</h1>
        <p>Generated by AITaxMD • ${new Date().toLocaleDateString()}</p>
      </div>
      <div class="content">${htmlContent}</div>
      <div class="no-print" style="margin-top: 30px; text-align: center;">
        <p><small>Use Ctrl+P or Cmd+P to print, or use your browser's File → Print menu</small></p>
      </div>
    </body>
    </html>
  `;

  printWindow.document.write(html);
  printWindow.document.close();
  printWindow.focus();
  
  // Auto-trigger print dialog after a short delay
  setTimeout(() => {
    printWindow.print();
  }, 500);
};

export function ExportButtons({ messageId, content, className }: ExportButtonsProps) {
  const [emailData, setEmailData] = useState({ email: "", note: "" });
  const [isEmailDialogOpen, setIsEmailDialogOpen] = useState(false);
  const [copied, setCopied] = useState(false);
  const { toast } = useToast();

  const exportPdfMutation = useMutation({
    mutationFn: async () => {
      // If no messageId, use simple client-side export
      if (!messageId) {
        exportToPrint(content);
        return { success: true };
      }
      
      // Otherwise use the server-based export
      const response = await fetch(`/api/export/pdf/message/${messageId}`, {
        method: "POST",
        credentials: "include",
      });
      
      if (!response.ok) {
        throw new Error("Failed to export PDF");
      }
      
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `tax-plan-${messageId}.pdf`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
      
      return blob;
    },
    onSuccess: () => {
      toast({
        title: messageId ? "PDF Downloaded" : "Print Dialog Opened",
        description: messageId ? 
          "Your tax plan has been exported as PDF." : 
          "Use your browser's print dialog to save as PDF.",
      });
    },
    onError: (error) => {
      toast({
        title: "Export Failed",
        description: error instanceof Error ? error.message : "Could not export PDF. Please try again.",
        variant: "destructive",
      });
    },
  });

  const shareEmailMutation = useMutation({
    mutationFn: async (data: { recipientEmail: string; senderNote: string }) => {
      return apiRequest("POST", "/api/share/email", {
        messageId,
        recipientEmail: data.recipientEmail,
        senderNote: data.senderNote,
      });
    },
    onSuccess: () => {
      setIsEmailDialogOpen(false);
      setEmailData({ email: "", note: "" });
      toast({
        title: "Email Sent",
        description: "Tax plan has been shared via email.",
      });
    },
    onError: () => {
      toast({
        title: "Share Failed",
        description: "Could not send email. Please try again.",
        variant: "destructive",
      });
    },
  });

  const handleCopyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(content);
      setCopied(true);
      toast({
        title: "Copied to Clipboard",
        description: "Tax plan content has been copied.",
      });
      setTimeout(() => setCopied(false), 2000);
    } catch (error) {
      toast({
        title: "Copy Failed",
        description: "Could not copy to clipboard.",
        variant: "destructive",
      });
    }
  };

  const handleEmailShare = () => {
    if (!emailData.email.trim()) {
      toast({
        title: "Email Required",
        description: "Please enter a recipient email address.",
        variant: "destructive",
      });
      return;
    }

    shareEmailMutation.mutate({
      recipientEmail: emailData.email,
      senderNote: emailData.note,
    });
  };

  return (
    <div className={`flex gap-2 ${className}`}>
      {/* Copy to Clipboard */}
      <Button
        variant="outline"
        size="sm"
        onClick={handleCopyToClipboard}
        disabled={copied}
        data-testid={`copy-button-${messageId}`}
      >
        {copied ? (
          <>
            <Check className="w-4 h-4 mr-2" />
            Copied
          </>
        ) : (
          <>
            <Copy className="w-4 h-4 mr-2" />
            Copy
          </>
        )}
      </Button>

      {/* Show PDF button for tax reports regardless of messageId */}
      {isTaxReport(content) && (
        <Button
          variant="outline"
          size="sm"
          onClick={() => exportPdfMutation.mutate()}
          disabled={exportPdfMutation.isPending}
          data-testid={`pdf-button-${messageId || 'simple'}`}
        >
          {exportPdfMutation.isPending ? (
            <>
              <Loader2 className="w-4 h-4 mr-2 animate-spin" />
              {messageId ? 'Exporting...' : 'Opening...'}
            </>
          ) : (
            <>
              <Download className="w-4 h-4 mr-2" />
              {messageId ? 'PDF' : 'Print PDF'}
            </>
          )}
        </Button>
      )}

      {/* DISABLED: Out-of-scope Email Share feature
      <Dialog open={isEmailDialogOpen} onOpenChange={setIsEmailDialogOpen}>
        <DialogTrigger asChild>
          <Button
            variant="outline"
            size="sm"
            data-testid={`email-button-${messageId}`}
          >
            <Mail className="w-4 h-4 mr-2" />
            Email
          </Button>
        </DialogTrigger>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Share Tax Plan via Email</DialogTitle>
            <DialogDescription>
              Send this tax planning strategy to someone via email.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4">
            <div>
              <Label htmlFor="email">Recipient Email</Label>
              <Input
                id="email"
                type="email"
                placeholder="recipient@example.com"
                value={emailData.email}
                onChange={(e) => setEmailData(prev => ({ ...prev, email: e.target.value }))}
                data-testid="email-input"
              />
            </div>
            <div>
              <Label htmlFor="note">Personal Note (Optional)</Label>
              <Textarea
                id="note"
                placeholder="Add a personal message..."
                value={emailData.note}
                onChange={(e) => setEmailData(prev => ({ ...prev, note: e.target.value }))}
                rows={3}
                data-testid="note-input"
              />
            </div>
          </div>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setIsEmailDialogOpen(false)}
              data-testid="cancel-email"
            >
              Cancel
            </Button>
            <Button
              onClick={handleEmailShare}
              disabled={shareEmailMutation.isPending}
              data-testid="send-email"
            >
              {shareEmailMutation.isPending ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  Sending...
                </>
              ) : (
                <>
                  <Share2 className="w-4 h-4 mr-2" />
                  Send Email
                </>
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
      */}
    </div>
  );
}